server:
  port: 8080

spring:
  application:
    name: api-gateway

  # Config server (optional)
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        # Auth service (no auth filter)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        # Zone service (protected)
        - id: zone-service
          uri: lb://zone-service
          predicates:
            - Path=/api/zones/**
          filters:
            - name: Authentication

        # Sensor service (protected)
        - id: sensor-service
          uri: lb://sensor-service
          predicates:
            - Path=/api/sensors/**
          filters:
            - name: Authentication

        # Crop Inventory service (protected)
        - id: crop-service
          uri: lb://crop-inventory-service
          predicates:
            - Path=/api/crops/**
          filters:
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: "a74138c70e93061c2d3d93f941e6295b88fcc694ab2d525d1c001948f6d4ee2a"

management:
  # Enable the gateway actuator endpoint
  endpoint:
    gateway:
      enabled: true       # allows the /gateway actuator endpoints to work
      # access: read-only # alternative option if you want only GET access
  endpoints:
    web:
      exposure:
        include: health, info, gateway   # expose the gateway endpoint over HTTP
