jwt:
  secret: "a74138c70e93061c2d3d93f941e6295b88fcc694ab2d525d1c001948f6d4ee2a"

spring:
  cloud:
    gateway:
      routes:
        - id: zone-service
          uri: lb://ZONE-MANAGEMENT-SERVICE  
          predicates:
            - Path=/api/zones/**
          filters:
            - AuthenticationFilter

        - id: sensor-service
          uri: lb://SENSOR-SERVICE           
          predicates:
            - Path=/api/sensors/**
          filters:
            - AuthenticationFilter

        - id: crop-service
          uri: lb://CROP-INVENTORY-SERVICE   
          predicates:
            - Path=/api/crops/**
          filters:
            - AuthenticationFilter
