server:
  port: 8083

spring:
  application:
    name: automation-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/agms_automation_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

automation:
  thresholds:
    temperature: 30.0
    humidity: 40.0

logging:
  level:
    com.agms.automation_service: DEBUG
