server:
  port: 8082

spring:
  application:
    name: sensor-service  
  jackson:
    serialization:
      write-dates-as-timestamps: false   

external:
  iot:
    base-url: http://104.211.95.241:8080/api
    username: root
    password: 1234

telemetry:
  fetch-interval: 10000

logging:
  level:
    com.agms.sensor_telemetry_service: DEBUG
